#!/usr/bin/env python3

import subprocess as bash
import os

# Styling functionality
class Style:

    BLACK   = '\033[30m'
    RED     = '\033[31m'
    GREEN   = '\033[32m'
    YELLOW  = '\033[33m'
    BLUE    = '\033[34m'
    MAGENTA = '\033[35m'
    CYAN    = '\033[36m'
    WHITE   = '\033[37m'
    
    BG_BLACK   = '\033[40m'
    BG_RED     = '\033[41m'
    BG_GREEN   = '\033[42m'
    BG_YELLOW  = '\033[43m'
    BG_BLUE    = '\033[44m'
    BG_MAGENTA = '\033[45m'
    BG_CYAN    = '\033[46m'
    BG_WHITE   = '\033[47m'

    BOLD = '\033[1m'
    UNDERLINE  = '\033[4m'
    RESET = '\033[0m'


def style(text, color=Style.BLACK, bg=Style.BG_WHITE, bold=True, underline=False, reset=Style.RESET):

    bold_text = Style.BOLD if bold else "" 
    underline_text = Style.UNDERLINE if underline else ""
    return (f"{bold_text}{underline_text}{bg}{color}{text}{reset}")


# Main function
def build():

    # Input function
    def question():

            return input(style(">> ", color=Style.MAGENTA)).lower().strip()

    # Project name
    print(style("Choose a project name", color=Style.CYAN))
    project_name = question()

    # Pm
    print(style("\ncreate with npm or bun? (q/w/e/r)", color=Style.CYAN))

    print(style("npm / q", color=Style.MAGENTA))
    print(style("yarn / w", color=Style.MAGENTA))
    print(style("pnpm / e", color=Style.MAGENTA))
    print(style("bun / r", color=Style.MAGENTA))

    package_manager = question()

    if (package_manager == "q"):
        package_manager = "npm"
    elif (package_manager == "w"):
        package_manager = "yarn"
    elif (package_manager == "e"):
        package_manager = "pnpm"
    elif (package_manager == "r"):
        package_manager = "bun"
    else:
        package_manager = "npm"

    # Framework choice
    print(style("\nChoose a framework (q/w)", color=Style.CYAN))

    print(style("React / q", color=Style.BLUE))
    print(style("Vue / w", color=Style.GREEN))

    project_framework = question()

    if (project_framework == "q"):
        project_framework = "react"
    elif (project_framework == "w"):
        project_framework = "vue"


    # Create directory
    project_path = os.path.abspath(project_name)
    os.makedirs(project_path, exist_ok=True)


    # Build files function
    def build_files(files):

        for filename, content in files.items():

            script = f"cat <<'EOF' > {filename}\n{content}\nEOF"
            bash.run(script, shell=True, cwd=project_path)
        
        bash.run(f"{package_manager} install", shell=True, cwd=project_path)


    # React build
    if (project_framework == "react"):

        # Add libs
        print(style("\nAdd react-router-dom? (y/n)", color=Style.CYAN))
        react_router_dom = question()

        print(style("\nAdd Sass? (y/n)", color=Style.CYAN))
        sass = question()


        if (react_router_dom == "y"):
            
            react_router_dom = ',\n    "react-router-dom": "^7.13.0"'
        else:
            react_router_dom = ''


        if (sass == "y"):

            sass = ',\n    "sass-embedded": "^1.97.3"'
        else:
            sass = ''


        # Files for React project
        index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{project_name}</title>
</head>
    <body>
        <div id="root"></div>
            <script type="module" src="./Init.jsx"></script>
    </body>
</html>"""
        
        vite_config = """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
    plugins: [react()],
})"""
        
        package_json = f"""{{"name": "{project_name}",
"private": true,
"version": "0.0.0",
"type": "module",
"scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
}},
"dependencies": {{
    "react": "^18.2.0",
    "react-dom": "^18.2.0"{react_router_dom}
}},
"devDependencies": {{
    "@types/react": "^18.2.0",
    "@types/react-dom": "^18.2.0",
    "@vitejs/plugin-react": "^4.0.0",
    "vite": "^4.4.0"{sass}
}}
}}"""
        
        init_jsx = """import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
    <React.StrictMode>
        <App />
    </React.StrictMode>,
)"""
        
        app_jsx = f"""import React from 'react'

var App = function () {{
    return (
        <>{project_name}</>
    )
}}

export default App"""
        
        git_ignore = f"""# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?"""

        files = {
            "index.html": index_html,
            "vite.config.js": vite_config,
            "package.json": package_json,
            "Init.jsx": init_jsx,
            "App.jsx": app_jsx,
            ".gitignore": git_ignore
        }

        build_files(files)


    # Vue build
    elif (project_framework == "vue"):

        # Add libs
        print(style("\nAdd vue-router? (y/n)", color=Style.CYAN))
        vue_router = question()

        print(style("\nAdd Sass? (y/n)", color=Style.CYAN))
        sass = question()


        if (vue_router == "y"):
            
            vue_router = ',\n    "vue-router": "^5.0.1"'
        else:
            vue_router = ''


        if (sass == "y"):

            sass = ',\n    "sass-embedded": "^1.97.3"'
        else:
            sass = ''


        # Files for Vue project
        index_html =    f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{project_name}</title>
</head>
    <body>
        <div id="root"></div>
            <script type="module" src="./Init.js"></script>
    </body>
</html>"""
        
        vite_config = f"""import {{ defineConfig }} from 'vite'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'

export default defineConfig({{
  plugins: [
    vue(),
    vueDevTools(),
  ]
}})"""

        package_json = f"""{{
"name": "{project_name}",
"version": "0.0.0",
"private": true,
"type": "module",
"scripts": {{
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
}},
"dependencies": {{
    "vue": "^3.5.27"{vue_router}
}},
"devDependencies": {{
    "@vitejs/plugin-vue": "^6.0.3",
    "vite": "^7.3.1",
    "vite-plugin-vue-devtools": "^8.0.5"{sass}
}},
"engines": {{
    "node": "^20.19.0 || >=22.12.0"
}}
}}"""

        init_js = f"""import {{ createApp }} from 'vue'
import App from './App.vue'

createApp(App).mount('#root')"""
        
        app_vue = f"""<script setup></script>

<template>{project_name}</template>

<style scoped></style>"""
        
        git_ignore = f"""# Logs
logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
.DS_Store
dist
dist-ssr
coverage
*.local

# Editor directories and files
.vscode/*
!.vscode/extensions.json
.idea
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?

*.tsbuildinfo

.eslintcache

# Vite
*.timestamp-*-*.mjs"""

        files = {
            "index.html": index_html,
            "vite.config.js": vite_config,
            "package.json": package_json,
            "Init.js": init_js,
            "App.vue": app_vue,
            ".gitignore": git_ignore
        }

        build_files(files)


# Entry point
if __name__ == "__main__":

    try:
        build()

    except:
        print(style("!!! Exit !!!", color=Style.RED))
