#!/usr/bin/env python3

import subprocess as bash
import os

indent_first = '\n        '
indent = ',\n        '

# Frontend libs versions
react_router_dom_version = indent + '"react-router-dom": "^7.13.0"'
vue_router_version = indent + '"vue-router": "^5.0.1"'
pinia_version = indent + '"pinia": "^3.0.4"'
sass_version =  indent + '"sass-embedded": "^1.97.3"'

# Backend libs versions
express_version = indent_first + '"express": "^4.19.0"'
fastify_version = indent_first + '"fastify": "^4.26.0"'
hono_version = indent_first + '"hono": "^4.0.0"' + indent + '"@hono/node-server": "^1.8.0"'
nodemon_version = indent_first + '"nodemon": "^3.1.0"'

# Styling functionality
class Style:

    BLACK   = '\033[30m'
    RED     = '\033[31m'
    GREEN   = '\033[32m'
    YELLOW  = '\033[33m'
    BLUE    = '\033[34m'
    MAGENTA = '\033[35m'
    CYAN    = '\033[36m'
    WHITE   = '\033[37m'
    
    BG_BLACK   = '\033[40m'
    BG_WHITE   = '\033[47m'

    BOLD = '\033[1m'
    UNDERLINE  = '\033[4m'
    RESET = '\033[0m'

def style(text, color=Style.BLACK, bg=Style.BG_WHITE, bold=True, underline=False, reset=True):

    bold_text = Style.BOLD if bold else "" 
    underline_text = Style.UNDERLINE if underline else ""
    reset_colors = Style.RESET if reset else ""

    return (f"{bold_text}{underline_text}{bg}{color} {text} {reset_colors}")

# Main function
def build():

    # Build files function
    def build_files(files):

        for filename, content in files.items():

            script = f"cat <<'EOF' > {filename}\n{content}\nEOF"
            bash.run(script, shell=True, cwd=project_path)
    
    # Input function
    def answer():

        return input(style(">>", color=Style.WHITE, bg=Style.BG_BLACK)).lower().strip()

    # Print functions        
    def question(text : str):

        return print(style(f"{text}", color=Style.CYAN))

    def advice(text : str):

        return print(style(f"{text}", color=Style.GREEN, bg=Style.BG_BLACK))

    # Side
    question('Choose (q/w)')

    print(style('Frontend / q', color=Style.RED))
    print(style('Backend / w', color=Style.BLACK))

    side = answer()

    if (side == "q"):

        side = "frontend"

    else:
        side = "backend"

    # Project name
    question("Choose a project name")

    project_name = answer()

    # Pm
    question("Choose pm (q/w/e/r)")

    print(style("npm / q", color=Style.RED))
    print(style("yarn / w", color=Style.MAGENTA))
    print(style("pnpm / e", color=Style.YELLOW))
    print(style("bun / r", color=Style.BLACK))

    package_manager = answer()

    match (package_manager):

        case "q":

            package_manager = "npm"

        case "w":

            package_manager = "yarn"

        case "e":

            package_manager = "pnpm"

        case "r":

            package_manager = "bun"

        case _:
            package_manager = "npm"

    if (package_manager == "npm"):

        run_script = "npm run dev"
    else:
        run_script = f"{package_manager} dev"

    # Create directory
    project_path = os.path.abspath(project_name)
    bash.run(f"mkdir {project_name}", shell=True)

    # .gitignore file
    git_ignore = f"""logs
*.log
npm-debug.log*
yarn-debug.log*
yarn-error.log*
pnpm-debug.log*
lerna-debug.log*

node_modules
dist
dist-ssr
*.local

.vscode/*
!.vscode/extensions.json
.idea
.DS_Store
*.suo
*.ntvs*
*.njsproj
*.sln
*.sw?"""

    # Frontend build
    if (side == 'frontend'):

        # index.html file
        index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{project_name}</title>
</head>
    <body>
        <div id="root"></div>
        <script type="module" src="./App.js"></script>
    </body>
</html>"""

        # Framework choice
        question("Choose a framework (q/w)")

        print(style("Vanilla JS / q", color=Style.BLACK))
        print(style("React / w", color=Style.BLUE))
        print(style("Vue / r", color=Style.GREEN))

        project_framework = answer()

        match (project_framework):

            case "q":

                project_framework = "vanilla_js"

            case "w": 

                project_framework = "react"

            case "r":

                project_framework = "vue"

        # React build
        if (project_framework == "react"):

            # Add libs
            question("Add react-router-dom? (y/n)")

            react_router_dom = answer()

            question("Add Sass? (y/n)")

            sass = answer()

            if (react_router_dom == "y"):
                
                react_router_dom = react_router_dom_version

            else:
                react_router_dom = ''


            if (sass == "y"):

                sass = sass_version
                
            else:
                sass = ''


            # Files for React project
            index_html = f"""<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{project_name}</title>
</head>
    <body>
        <div id="root"></div>
        <script type="module" src="./App.jsx"></script>
    </body>
</html>"""

            vite_config = """import { defineConfig } from 'vite'
import react from '@vitejs/plugin-react'

export default defineConfig({
    plugins: [react()],
})"""
            
            package_json = f"""{{
    "name": "{project_name}",
    "private": true,
    "version": "0.0.0",
    "type": "module",
    "scripts": {{
        "dev": "vite",
        "build": "vite build",
        "preview": "vite preview"
    }},
    "dependencies": {{
        "react": "^18.2.0",
        "react-dom": "^18.2.0"{react_router_dom}
    }},
    "devDependencies": {{
        "@vitejs/plugin-react": "^4.0.0",
        "vite": "^4.4.0"{sass}
    }}
}}"""
            
            app_jsx = """import React from 'react'
import ReactDOM from 'react-dom/client'
import Main from './Main.jsx'

ReactDOM.createRoot(document.getElementById('root')).render(
    <React.StrictMode>
        <Main />
    </React.StrictMode>,
)"""

            main_jsx = f"""var Main = function () {{
    return (
        <>{project_name}</>
    )
}}
export default Main"""
            
            main_jsx_router = f"""import {{ RouterProvider, createBrowserRouter }} from "react-router-dom";
var Main = function () {{

    var routes = [
        {{
            path: "/",
            element: <>{project_name}</>
        }}    
    ]

    var router = createBrowserRouter(routes)
    return <RouterProvider router={{router}} />
}}
export default Main"""

            files = {
                "index.html": index_html,
                "vite.config.js": vite_config,
                "package.json": package_json,
                "App.jsx": app_jsx,
                "Main.jsx": main_jsx,
                ".gitignore": git_ignore
            }

            if (react_router_dom):

                files["Main.jsx"] = main_jsx_router

            build_files(files)

        # Vue build
        elif (project_framework == "vue"):

            # Add libs
            question("Add vue-router? (y/n)")

            vue_router = answer()

            question("Add Pinia? (y/n)")

            pinia = answer()

            question("Add Sass? (y/n)")

            sass = answer()

            if (vue_router == "y"):
                
                vue_router = vue_router_version

            else:
                vue_router = ''

            if (pinia == "y"):

                pinia = pinia_version
            
            else:
                pinia = ''

            if (sass == "y"):

                sass = sass_version

            else:
                sass = ''


            # Files for Vue project
            vite_config = f"""import {{ defineConfig }} from 'vite'
import vue from '@vitejs/plugin-vue'
import vueDevTools from 'vite-plugin-vue-devtools'

export default defineConfig({{
plugins: [
    vue(),
    vueDevTools(),
]
}})"""

            package_json = f"""{{
    "name": "{project_name}",
    "version": "0.0.0",
    "private": true,
    "type": "module",
    "scripts": {{
        "dev": "vite",
        "build": "vite build",
        "preview": "vite preview"
    }},
    "dependencies": {{
        "vue": "^3.5.27"{vue_router}{pinia}
    }},
    "devDependencies": {{
        "@vitejs/plugin-vue": "^6.0.3",
        "vite": "^7.3.1",
        "vite-plugin-vue-devtools": "^8.0.5"{sass}
    }},
    "engines": {{
        "node": "^20.19.0 || >=22.12.0"
    }}
}}"""

            app_js = f"""import {{ createApp }} from 'vue'
import Main from './Main.vue'
{"import router from './router.js'" if (vue_router) else ""}
{"import { createPinia } from 'pinia'" if (pinia) else ""}

createApp(Main){".use(router)" if (vue_router) else ""}{".use(createPinia())" if (pinia) else ""}.mount('#root')"""
            
            main_vue = f"""<script setup></script>

<template>{project_name}</template>

<style scoped></style>"""

            router_js = """import { createRouter, createWebHistory } from 'vue-router'

var router = createRouter({

    history: createWebHistory(import.meta.env.BASE_URL),
    routes: []
})
export default router
"""

            files = {
                "index.html": index_html,
                "vite.config.js": vite_config,
                "package.json": package_json,
                "App.js": app_js,
                "Main.vue": main_vue,
                ".gitignore": git_ignore
            }

            if (vue_router):

                files["router.js"] = router_js

            build_files(files)

        # Vanilla JS Build
        else:

            package_json = f"""{{
    "name": "{project_name}",
    "private": true,
    "version": "0.0.0",
    "type": "module",
    "scripts": {{
        "dev": "vite",
        "build": "vite build",
        "preview": "vite preview"
    }},
    "devDependencies": {{
        "vite": "^7.3.1"
    }}
}}"""

            app_js = f"""var root = document.querySelector('#root')
        
root.innerHTML = '{project_name}'"""

            files = {
                "index.html": index_html,
                "package.json": package_json,
                "App.js": app_js,
                ".gitignore": git_ignore
            }

            build_files(files)

        # Advice for frontend

    # Backend build
    elif (side == 'backend'):

        # Framework choice
        question("Chose a framework (q/w/e/r)")

        print(style('Vanilla JS / q', color=Style.BLACK))
        print(style('Express / w', color=Style.YELLOW))
        print(style('Fastify / e', color=Style.BLUE))
        print(style('Hono / r', color=Style.MAGENTA))

        project_framework = answer()

        match (project_framework):
            
            case "q":

                dependcies = ''

            case "w":

                dependcies = express_version

            case "e":

                dependcies = fastify_version

            case "r":

                dependcies = hono_version
            
            case _:
                dependcies = ''

        # Add libs
        question("Add nodemon? (y/n)")

        nodemon = answer()

        if (nodemon == "y"):

            dev_script = "nodemon index.js"
            nodemon = nodemon_version

        else:
            dev_script = "node --watch index.js"
            nodemon = ''

        # Files for backend project
        index_js_vanilla = f"""import http from 'node:http';
var server = http.createServer((req, res) => {{
    res.writeHead(200, {{ 'Content-Type': 'text/plain; charset=utf-8' }});

    if (req.url === '/') {{
        res.end('{project_name}');
    }}
}});

server.listen(3000, () => {{
    console.log('http://localhost:3000');
}});"""

        index_js_express = f"""import express from 'express';
var app = express();

app.get('/', (req, res) => res.send('{project_name}'));

app.listen(3000, () => console.log('http://localhost:3000'));"""

        index_js_fastify = f"""import Fastify from 'fastify';
var app = Fastify();

app.get('/', async () => '{project_name}');

app.listen({{ port: 3000 }}, () => console.log('http://localhost:3000'));"""        

        index_js_hono = f"""import {{ Hono }} from 'hono';
import {{ serve }} from '@hono/node-server';
var app = new Hono();

app.get('/', (c) => c.text('{project_name}'));

serve(app, () => console.log('http://localhost:3000'));"""

        package_json = f"""{{
    "name": "{project_name}",
    "version": "1.0.0",
    "description": "",
    "main": "index.js",
    "scripts": {{
        "dev": "{dev_script}"
    }},
    "dependencies": {{
        {dependcies} 
    }},
    "devDependencies": {{
        {nodemon}
    }},
    "keywords": [],
    "author": "",
    "license": "ISC",
    "type": "module"
}}"""

        match (project_framework):
            
            case "q":

                index_js = index_js_vanilla

            case "w":

                index_js = index_js_express

            case "e":

                index_js = index_js_fastify

            case "r":

                index_js = index_js_hono

            case _:
                index_js = index_js_vanilla

        files = {
            "index.js": index_js,
            "package.json": package_json,
            '.gitignore': git_ignore
        }

        build_files(files)

        bash.run("mkdir routes", shell=True, cwd=project_path)
        bash.run("mkdir controllers", shell=True, cwd=project_path)

        # Advice for backend project
        if (nodemon):

            match (package_manager):

                case "npm":

                    advice("npm install -g nodemon")

                case "yarn":

                    advice("yarn global add nodemon")

                case "pnpm":

                    advice("pnpm add -g nodemon")

                case "bun":

                    advice("bun add -g nodemon")

    # Advice
    advice(f"cd {project_name}")
    advice(f"{package_manager} install")
    advice(run_script)

# Entry point
if __name__ == "__main__":

    try:
        build()

    except:
        print()
        print(style("!!! Exit !!!", color=Style.RED, bg=Style.BG_BLACK))
